### ISSUE TITLE
`struct.error: unpack requires a bytes object of length 35`

### ISSUE THREAD

**Issue by stefan-jansen** [cswaney/prickle#2]
Hi @cswaney, thanks for putting this module together! I tried to run it with this sample file: ftp://emi.nasdaq.com/ITCH/GIS/S022717-v50.txt.gz using: 
```
pk.unpack(fin='S022717-v50.txt',
          ver=5.0,
          date='022717',
          fout='itch.hdf5',
          nlevels=5,
          names=['GOOG', 'AAPL'],
          method='hdf5')
```
but am getting:
```
Traceback (most recent call last):
  File ".../nasdaq_itch.py", line 34, in <module>
    method='hdf5')
  File "/home/src/prickle/prickle/core.py", line 1389, in unpack
    message = get_message(message_bytes, message_type, date, clock, ver)
  File "/home/src/prickle/prickle/core.py", line 1074, in get_message
    message = protocol(message_bytes, message_type, time, version)
  File "/home/src/prickle/prickle/core.py", line 1293, in protocol
    temp = struct.unpack('>HHHIQsI8sI', message_bytes)
struct.error: unpack requires a bytes object of length 35
```

Any suggestions?

**Comment by stefan-jansen** [comment]
I've submitted pull request to fix two format strings for v5.0: https://github.com/cswaney/prickle/pull/3.
